title_name = "Carrier Command: Gaea Mission"
title_id = "4D4B07D6" # MK-2006
hash = "D934234ED6CF93F5" # default.xex
#media_id = "758D9246" # Disc (Europe): http://redump.org/disc/50528

[[patch]]
    name = "Disable God Rays"
    desc = "Reduces extreme bloom when looking at the sun. Also removes sun flare effect."
    author = "Sowa_95"
    is_enabled = false

    [[patch.be32]]
        address = 0x8221201c
        value = 0x60000000
